### ISSUE TITLE
Store version?

### ISSUE THREAD

**Issue by m1ga** [appcelerator/kitchensink-v2#13]
Would be nice to have a compiled version inside the App/Play Store. So you can just download a version and see how features/UI elements look and behave without compiling a version

**Comment by hansemannn** [comment]
Not sure if this would go through AppStore validation though..

**Comment by TheeAndre** [comment]
I'm actually going to try this. It does have a few red flags that won't pass it.

**Comment by hansemannn** [comment]
Awesome @TheeAndre! It does - mainly the "this is no real app" thing. But maybe Apple understands the developer purpose, so if it's described correctly and listed in the correct category, it might actually be approved!

**Comment by TheeAndre** [comment]
@hansemannn I'll try it out this weekend. I'll keep you guys posted.

**Comment by hansemannn** [comment]
@TheeAndre Did you get it through?

**Comment by TheeAndre** [comment]
Never got past compiling the Kitchensink. A lot of errors somewhere. I've got time today so i'll try place it in the store.

**Comment by hansemannn** [comment]
Compile errors? Thats weird. I'm frequently building it with success, but please let me know what you are running into and we'll take a look.

**Comment by Topener** [comment]
@hansemannn yes we should! Should be released under the Appc name I think?

**Comment by TheeAndre** [comment]
That's a good idea. Mine didn't pass on the App Store. Something about it being a 'pointless' non value adding app. I'll check the response. I put it aside after that.

**Comment by hansemannn** [comment]
Closing issue since it is not really an issue. More discussion on Slack is welcome!
