### ISSUE TITLE
Cannot recover from the syntax error [app/styles/index.tss]

### ISSUE THREAD

**Issue by TheeAndre** [appcelerator/kitchensink-v2#19]
Hi,
I've just opened the repo in App Studio and i'm getting this error: "Cannot recover from the syntax error" in the index.tss file [app/styles/index.tss]

The file was update recently & had nothing in it before the update. Now it contains this code:

```
'TabGroup': {

}
```

**Comment by hansemannn** [comment]
Will try it out! iOS / Android / Windows?

**Comment by TheeAndre** [comment]
It's a code highlighted by Appcelerator 
Studio when you open the repo.

**Comment by hansemannn** [comment]
Maybe studio is unable to handle `'` instead of `"` ? That'd be an odd issue, let me check with the Studio team !

**Comment by hansemannn** [comment]
It was the white-space between `: {`. Fixed it and will push it now together with resolving all other Studio warnings.

**Comment by hansemannn** [comment]
Resolved as part of https://github.com/appcelerator/kitchensink-v2/commit/57cd5bc9baa3cc1892a502e9465a491c8ca15355, thanks for pinging us! :-)
