### ISSUE TITLE
Move to ES6

### ISSUE THREAD

**Issue by hansemannn** [appcelerator/kitchensink-v2#20]
We should move this project to ES6, especially for:

- Using classes
- Using arrow-operator `() =>`
- Using let / const vs. var
- Using ESLint

**Comment by nuno** [comment]
You have my vote!

**Comment by hansemannn** [comment]
@nuno Then go for it ;-) This is an open-source project!

**Comment by hansemannn** [comment]
Handled in https://github.com/appcelerator/kitchensink-v2/pull/28.
