### ISSUE TITLE
ES6 Support Issues

### ISSUE THREAD

**Issue by TheeAndre** [appcelerator/kitchensink-v2#38]
What do i need to setup or update on my environment (macOS) to get rid of the following errors?

```Syntax Error: unexpected token "import"```

```Syntax Error: unexpected token "export"```

**Comment by ewanharris** [comment]
Hey @TheeAndre can you provide some more info about when you're getting these errors? Is it when building kitchensink-v2, when running it on device/simulator?

**Comment by TheeAndre** [comment]
Hi @ewanharris,
I haven't run the build yet. I've opened kitchensink-v2 in the update Appcelerator Studio & it highlights these errors.

Axway Appcelerator Studio, build: 5.1.1.201809051655
(c) Copyright 2018 by Axway.  All Rights Reserved.

Build: jenkins-appcelerator-studio-titanium_studio-master-38 (master)
Date: 201809051655

**Comment by TheeAndre** [comment]
Thanks for the feedback. I'll track the ticket.
